### PR TITLE
Milestones/environment provisioning decommissioning

### PR DESCRIPTION
**Pull request by rpothin**
# Status

PR - Ready

# Description

* Initialization of the pipeline definitions for the provisioning and the decommissioning of the Power Platform environment
* Update of the README.md

# Issues

* #8 [IDEA] YAML files to automate the provisioning of a Power Platform environment with creation of the service connection
* #9 [IDEA] YAML files to automate the decommissioning of a Power Platform environment

# Test scenarios

* Creation of a Power Platform Environment and the associated Power Platform service endpoint in Azure DevOps using the **create-powerplatform-environment-and-service-endpoint.yml** pipeline definition
* Creation of a Power Platform service endpoint in Azure DevOps for an existing Power Platform environment using the **create-powerplatform-service-endpoint.yml** pipeline definition
* Deletion of a Power Platform Environment and the associated Power Platform service endpoint in Azure DevOps using the **delete-powerplatform-environment-and-service-endpoint.yml** pipeline definition
* Creation of a Power Platform service endpoint in Azure DevOps using the **delete-powerplatform-service-endpoint.yml** pipeline definition

# Changes include
- [X] Initialization of the **Pipelines** folder
- [X] Initialization of the **ServiceEndpoints** folder
- [X] Update of the README.md file

# Approval checklist
- [ ] Tests

### CODE REVIEW

**Comment by rpothin** [comment]
I already created the following issue to improve this solution: **#16 Use of a JSON template file of the Power Platform environment in the provisioning pipeline**

**Comment by BenediktBergmann** [comment]
Again sorry for the late response.

I do like your work! It looks really good. I couldn't find any obvious problem or things I would like to change. We might have to increase the documentation though. To make it a bit more clear what to use this for.

**Review by BenediktBergmann — COMMENTED** [review]
Looks good.

**Comment by rpothin** [comment]
Thank you very much for this feedback @BenediktBergmann.

For the documentation I agree. I will add a **What the solution covers for now** section in the README.md file before we merge this PR.

Did you already test the pipelines and the deployment process? Or did you just take a look at the PR content?

Thank you for your help 🙂

**Comment by rpothin** [comment]
Hey @BenediktBergmann,

We are back in the game with this pull request 🥳

You will find below a summary of what I have updated during the past days:
- Replaced the **Create Environment** task of the **Power Platform Build Tools** Azure DevOps extension due to all the instability we were facing by a reworked version of a PowerShell function I was working on few weeks ago for the AA4AM app setup
- Replaced the variables in the pipelines with a variable group and [**runtime parameters**](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script) - really interesting feature for manually trigger pipelines 😁
- Added a GitHub workflow to execute unit tests for PowerShell functions on pull requests to avoid some regressions in the future
- Updated the **README.md** file

Bonus points with the **New-DataverseEnvironment** PowerShell function:
- Does not create duplicate environments based on the name provided
- Can set a **description** and / or a **security group** on the environment created

I am really looking forward your feedbacks regarding this new version 😉

Have a nice weekend 😊

**Review by BenediktBergmann — DISMISSED** [review]
Looks good!

**Comment by rpothin** [comment]
@BenediktBergmann for your information I just added a missing step (update of the environment configuration file) in the set-up section of the README.md.

I will approve the PR myself this time to not bother you 😊

**Pull request merged**
